### ISSUE TITLE
Error while installing on hackrf

### ISSUE THREAD

**Issue by sourcepirate** [mappum/node-hackrf#2]
There is no doubt this is a really cool project. But when i tried to install it i ran into this error.

```
/usr/bin/hackrf -> /usr/lib/node_modules/hackrf/bin.js

> hackrf@2.2.0 install /usr/lib/node_modules/hackrf
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/hackrf/build'
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/os/threads_posix.o
../deps/libusb/libusb/os/threads_posix.c:24:0: warning: "_GNU_SOURCE" redefined [enabled by default]
 #  define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/deps/libusb/libusb/os/linux_netlink.o
../deps/libusb/libusb/os/linux_netlink.c: In function ‘linux_netlink_read_message’:
../deps/libusb/libusb/os/linux_netlink.c:311:5: warning: pointer targets in passing argument 1 of ‘linux_netlink_parse’ differ in signedness [-Wpointer-sign]
     &busnum, &devaddr);
     ^
../deps/libusb/libusb/os/linux_netlink.c:196:12: note: expected ‘char *’ but argument is of type ‘unsigned char *’
 static int linux_netlink_parse(char *buffer, size_t len, int *detached, const char **sys_name,
            ^
  AR(target) Release/obj.target/deps/usb.a
  COPY Release/usb.a
  CC(target) Release/obj.target/libhackrf/src/hackrf.o
../src/hackrf.c: In function ‘hackrf_open_usb’:
../src/hackrf.c:421:2: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘ssize_t’ [-Wformat=]
  printf("Number of USB devices: %ld\n", list_length);
  ^
../src/hackrf.c: In function ‘hackrf_set_freq_explicit’:
../src/hackrf.c:1046:2: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
  if (if_freq_hz < 2150000000 || if_freq_hz > 2750000000) {
  ^
../src/hackrf.c:1046:2: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
  AR(target) Release/obj.target/hackrf.a
  COPY Release/hackrf.a
  CXX(target) Release/obj.target/hackrf/src/bindings.o
../src/bindings.cc:8:20: error: ‘FunctionCallbackInfo’ does not name a type
 void Devices(const FunctionCallbackInfo<Value>& args) {
                    ^
../src/bindings.cc:8:20: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../src/bindings.cc:8:40: error: expected ‘,’ or ‘...’ before ‘<’ token
 void Devices(const FunctionCallbackInfo<Value>& args) {
                                        ^
../src/bindings.cc: In function ‘void Devices(int)’:
../src/bindings.cc:10:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
   HandleScope scope(isolate);
                            ^
../src/bindings.cc:10:28: note: candidates are:
In file included from /home/plasmashadow/.node-gyp/0.10.40/src/node.h:62:0,
                 from ../node_modules/nan/nan.h:24,
                 from ../src/bindings.cc:1:
/home/plasmashadow/.node-gyp/0.10.40/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
   HandleScope(const HandleScope&);
   ^
/home/plasmashadow/.node-gyp/0.10.40/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/home/plasmashadow/.node-gyp/0.10.40/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
   HandleScope();
   ^
/home/plasmashadow/.node-gyp/0.10.40/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../src/bindings.cc:34:3: error: ‘args’ was not declared in this scope
   args.GetReturnValue().Set(Device::NewInstance(device));
   ^
../src/bindings.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
../src/bindings.cc:41:46: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [8], void (&)(int))’
   NODE_SET_METHOD(exports, "devices", Devices);
                                              ^
../src/bindings.cc:41:46: note: candidate is:
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/bindings.cc:1:
/home/plasmashadow/.node-gyp/0.10.40/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
 void SetMethod(target_t obj, const char* name,
      ^
/home/plasmashadow/.node-gyp/0.10.40/src/node.h:112:6: note:   template argument deduction/substitution failed:
../src/bindings.cc:41:46: note:   cannot convert ‘Devices’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
   NODE_SET_METHOD(exports, "devices", Devices);
                                              ^
make: *** [Release/obj.target/hackrf/src/bindings.o] Error 1
make: Leaving directory `/usr/lib/node_modules/hackrf/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-61-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/hackrf
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! hackrf@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hackrf@2.2.0 install script.
npm ERR! This is most likely a problem with the hackrf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hackrf
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-61-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "hackrf"
npm ERR! cwd /home/plasmashadow
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by mafintosh** [comment]
Based on your output I'm assuming you're compiling on linux? which version of g++ do you have?

**Comment by ralphtheninja** [comment]
@mafintosh I think this is related to node version `0.10.x` (I had the same error on that node version). I suspect that some stuff in `src/` should use some `nan` abstractions, don't have any more details now though.

**Comment by watson** [comment]
@mappum With the prebuilds I think this issue is solved right?

**Comment by mafintosh** [comment]
Yes
